---
- hosts: localhost
  tasks:
  - name: Create temp directory for doing work in
    command: mktemp -d /tmp/mytempdir-XXXXXX
    register: mktemp
    changed_when: False

  - set_fact:
      tempdir: "{{ mktemp.stdout }}"

  - name: Cleanup temp directory
    file:
      path: "{{ tempdir }}"
      state: absent

